//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresClienUsu
    {
        public long Id { get; set; }
        public Nullable<long> IdPrestamo { get; set; }
        public Nullable<long> IdUsuario { get; set; }
        public Nullable<long> IdCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Prestamo Prestamo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
