//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prestamo()
        {
            this.Movimientos = new HashSet<Movimiento>();
            this.PresClienUsus = new HashSet<PresClienUsu>();
        }
    
        public long Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<float> Monto { get; set; }
        public Nullable<int> Cuotas { get; set; }
        public Nullable<float> Interes { get; set; }
        public Nullable<byte> SemQuinSem { get; set; }
        public Nullable<long> IdCliente { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimiento> Movimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresClienUsu> PresClienUsus { get; set; }
    }
}
