//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.PresClienUsus = new HashSet<PresClienUsu>();
        }
    
        public long Id { get; set; }
        [Display(Name ="Nombre y Apellido")]
        public string ApyNom { get; set; }
        public string DNI { get; set; }
        public string Domicilio { get; set; }
        [Display(Name = "Telefono Celular")]
        public string Celular { get; set; }
        [Display(Name = "Usuario")]
        [Required]
        public string Usuario1 { get; set; }
        [Required]
        [Display(Name = "Contraseña")]
        public string Password { get; set; }
        [Display(Name = "Zona")]
        public Nullable<long> IdZona { get; set; }
        public Nullable<byte> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresClienUsu> PresClienUsus { get; set; }
        public virtual Zona Zona { get; set; }
    }
}
